apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-browser
  labels:
    app: registry-browser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-browser
  template:
    metadata:
      labels:
        app: registry-browser
    spec:
      containers:
      - name: registry-browser-frontend
        image: local-registry:5002/registry-browser:latest
        env:
        - name: DOCKER_REGISTRY_URL
          value: "http://registry-browser-backend:5000"
        - name: ENABLE_DELETE_IMAGES
          value: "true"
        - name: PUBLIC_REGISTRY_URL
          value: "localhost:5000"
        ports:
        - containerPort: 8080
      - name: registry-browser-backend
        image: registry:2
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        ports:
        - containerPort: 5000
