version: "3"

services:

  frontend:
    build: .
    environment:
      - "DOCKER_REGISTRY_URL=http://${ROOST_CLUSTER_IP}:5002"
      - "ENABLE_DELETE_IMAGES=true"
      - "SCRIPT_NAME=/browser"
      - "RAILS_RELATIVE_URL_ROOT=/browser"
    ports:
      - "30001:8080"

  backend:
    image: registry:2
    environment:
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
    ports:
      - "30015:5002"
