version: "3"

services:

  frontend:
    build: .
    environment:
      - "DOCKER_REGISTRY_URL=$ROOST_CLUSTER_IP:5000"
      - "ENABLE_DELETE_IMAGES=true"
    ports:
      - "3000:8080"

  backend:
    image: registry:2
    environment:
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
    ports:
      - "3001:5000"
