apiVersion: v1
kind: Service
metadata:
  name: registry-browser-lb
  labels:
    app: registry-browser
spec:
  selector:
    app: registry-browser
  ports:
    - name: Frontend
      port: 3000
      targetPort: 8080
      nodePort: 30050
    - name: Backend
      port: 3001
      targetPort: 5000
      nodePort: 30060
  type: NodePort
